### ISSUE TITLE
No Main Attribute

### ISSUE THREAD

**Issue by Dokman** [SoapboxRaceWorld/soapbox-race-core#25]
the gradle build doesn't builkd with a main script to work with

**Comment by LeoCodes21** [comment]
I am working on installation documentation. When it's done, I'll let you know.

**Comment by Dokman** [comment]
i just only need the main class hahahaha

**Comment by LeoCodes21** [comment]
The server is not an executable JAR file. Wait for documentation.

**Comment by Dokman** [comment]
oh then is a library that engage the server hahahaha

**Comment by Dokman** [comment]
Any news on the installation wiki? I can make for you the markdown

**Comment by Dokman** [comment]
@LeoCodes21

**Comment by LeoCodes21** [comment]
No. It will be done when I have the time.
