### ISSUE TITLE
Channels do not work and no other players are visible

### ISSUE THREAD

**Issue by LightRO** [SoapboxRaceWorld/soapbox-race-core#57]
Hello, everybody,

I know you don't want to give support. 
But I'm hoping that you could help me out here.
Now that I was able to fix the remaining errors by understanding the code, there are still 2 errors left that I could not solve so far. One of them is the problem that I don't see any other players on the map let alone in the world and that the channel for the text chat is not shown, although it was created in the DB.

I use the restAPI, SaslAuth Api, core and openfire from you. The databases were also used, installed and adapted by you. 

Could you give me some help here?

Many thanks and many greetings,
LightRO

**Comment by LeoCodes21** [comment]
No. I have already said that no support will be provided. Everything will be explained in the documentation when it is completed.
