### ISSUE TITLE
Achievemt Data SQL Throws errors because badge_definition is not locked

### ISSUE THREAD

**Issue by AidenWTF** [SoapboxRaceWorld/soapbox-race-core#82]
https://github.com/SoapboxRaceWorld/soapbox-race-core/blob/master/sql-new/achievement-data.sql

**Comment by LeoCodes21** [comment]
Thanks for the report. The scripts in that directory will be replaced (or removed entirely) in the next release. At that point, this shouldn't be an issue, although these scripts have been used several times without any problems.
