### ISSUE TITLE
Can't seem to recieve a cryptoticket

### ISSUE THREAD

**Issue by JaspervRijbroek** [SoapboxRaceWorld/soapbox-race-core#84]
When testing a new instance of the server locally the client doesn't seem it wants to retrieve a cryptoticket before connecting to the udp server, might this be because of the absence of a xmpp server?

**Comment by LeoCodes21** [comment]
Correct. I'm not sure how you could get in the world at all without an XMPP server, though. Usually the game just immediately complains about not having a connection.

**Comment by JaspervRijbroek** [comment]
I have noticed that after the first heartbeat it will continue, then I will try to setup the XMPP server!
Thanks alot :D

**Comment by JaspervRijbroek** [comment]
Another possible related question,
I have now setup a simple XMPP server, however when trying to add components to the car (from catalog) it remains on please wait, so it won't let me select any products.

Is this related to the XMPP server?

**Comment by LeoCodes21** [comment]
It's probably not related to XMPP. More likely is a database issue, but I'm not sure.

**Comment by JaspervRijbroek** [comment]
Seems like if the personaID is below 100 it doesn't work as it won't load in the persona info.
