### ISSUE TITLE
Can anyone give me some advice on how to build a nfsw server?

### ISSUE THREAD

**Issue by TriGunMaster** [SoapboxRaceWorld/soapbox-race-core#89]
Can you give detailed instructions on the different software versions used eg.
- MVN and JAVA Version at "mvn package" on Core Server
- MVN and JAVA Version at "mvn verify" on Openfire, openfire-restAPI-plugin and openfire-nonSaslAuthentication-plugin
- JAVA Version at runnable Server Core jar and Server Openfire

Also I found that when I add the plugin The openfire-restAPI-plugin in Openfire cannot be accessed due to an error plugin.

However, the choice of branch and fork for each person is still confusing because git master doesn't provide complete components such as no SQL structure, location to set in database of SOAPBOX and openfire, so I had to try loading git by looking at Forks list and load them all to try. It shows that important data files are scattered among each person's forks, although I've gathered them until I'm sure there are many. But being addicted to various problems makes me think that Is there any information I need to set up the server that I don't know yet?

I have tried installing both in Ubuntu 18.04 and Windows 10. The basic tools that I installed and tried are as follows.
- mvn 3.0.0 - 3.8.1
- java version 8, 9, 11
- redis-server
- openfire 4.5.0 < default, 4.6.1
- mysql 8

I initially followed the instructions in the wiki, but found that there were many problems that could not be solved with git master alone. I've tried searching for older versions like Soapbox Race World Core 1.0.0 - 1.0.3 and put it in a test build but it still doesn't work. So I'd like to ask for some advice on setting up and including sql structure, will that help me?

**Comment by hypernucle** [comment]
Hello, you can try this guide:
https://github.com/berkayylmao/setting-up-sbrw

**Comment by TriGunMaster** [comment]
> Hello, you can try this guide:
> https://github.com/berkayylmao/setting-up-sbrw

Thank you for recommending I'll try to set it up again next time.
