### ISSUE TITLE
Building a server today... outdated tutorial.

### ISSUE THREAD

**Issue by 0P3N50URC3-F0R3V3R** [SoapboxRaceWorld/soapbox-race-core#95]
This: https://github.com/berkayylmao/setting-up-sbrw

tutorial Is not entirely up to date, since there is a very lot of repositories/dependencies in POM.XML is not correct anymore, you need to fix it manually, but when you are build up your server it wont work with the provided openfire version(the only one was i able to use is not SBRW openfire its the original, not the one i built, i copyed over the rest and other plugins to make them work and it seems that it works, but in reality only the login system works..) The server starts up, working, i can go ingame singleplayer, but no POwerups or any type of multiplayer, i did the tutorial modnet part, but beside that what i need? i need to need to install beside something in the tutorial? How can i make work multiplayer and powerups my own server? Also why is that that sbrw custom build openfire wont work? 

I added my log file of the core. Please check it for me, i cannot ask any help from anywhere... 

If i use the custom built openfire 4.5.0 Alpha then i get this warnings about SSL or something... : 

![kép_2021-12-14_220456](https://user-images.githubusercontent.com/94479523/146079114-42b1933c-694d-41a9-b7f3-29441e479279.png)

After this it will work; however the core wont and it causes error messages both openfire and the program itself then the core.jar crashes.

Here is the logs::
CORE j jar error: [core.log](https://github.com/SoapboxRaceWorld/soapbox-race-core/files/7714771/core.log)
OPENFIRE error log: [openfire.log](https://github.com/SoapboxRaceWorld/soapbox-race-core/files/7714780/openfire.log)

Then it crashes, this is the recommended openfire the 4.5.0 alpha from the tutorial. i am using everything like in the tutorial even the folders is the same.

MY OTHER solution was that i use the latest version of openfire(4.6.5)... now, then it is working without errors, but the MODNET part of the tutorial is a bit missing parts and not too concrete... i have an XMPP server with index.json and i added all neceserry part of the moddong parameters for the modnet, but.. it is not clear i need to install some modnet framework somehow on windows or how should i use that? I can go ingame but no powerups nor multiplayer, nothing... I am trying to host this of my small friend comminity privately on a VPN... Also freeroam server is not working either the players not seeing each other ect ect... 

Can someone help me? I WOULD RELLY want to do this but no one is willing to help me... i did tried to be as much detailed as possible, but here is an other sum:
- OS: Windows server 2012R2 (Virtual with 6GB ram and 12 VCore)
- OpenJava 10
- Mysql 8.0.23 - that is on the tutorial
- Apache MAven
- GO installed, and all programs are in the reuied paths i can now compile without a problem my only problem is that this is not working well at all... 

Can you people help me? If there is needed some more details just yell. I can provide any log and thingy...

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Nevermind, i did solvet id.

**Comment by dbasset31** [comment]
> Nevermind, i did solvet id.

How please ?

**Comment by striker890** [comment]
> Nevermind, i did solvet id.

💩

**Comment by 0P3N50URC3-F0R3V3R** [comment]
I dont understand the thumbs down... Think a bit striker890...  i needed to rebuild the entire tutorial link by link, and add every cert file into java, change resources that depends on online sources that are not avaliable anymore, do redirects in maven, cert file modify in java, rething patch ect ect... so what i did is a complete OS level SDK and that i was able to compile it... you can have that version in my precompiled repo. If you want i can post the Preconfigured SDK to compile yourself, but that is HUGE; based on an OracleVM... the fix itself would require a tutorial long as the outdated tutorial itself if not longer... All i can do is to provide my result or repo and VM... If anyone want.
